/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unit_tests/_unittests.check" instead.
 */

#include <check.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "s21_string.h"

START_TEST(s21_insert_test1) {
  const char *source = "Hello,!";
  const char *insertion = " How are you?";
  char *result = s21_insert(source, insertion, 6);
  ck_assert_str_eq(result, "Hello, How are you?!");
  free(result);
}
END_TEST

START_TEST(s21_insert_test2) {
  const char *source = "abcdef";
  const char *insertion = "123";
  char *result = s21_insert(source, insertion, 0);
  ck_assert_str_eq(result, "123abcdef");
  free(result);
}
END_TEST

START_TEST(s21_insert_test3) {
  const char *source = "abcdef";
  const char *insertion = "123";
  char *result = s21_insert(source, insertion, strlen(source));
  ck_assert_str_eq(result, "abcdef123");
  free(result);
}
END_TEST

START_TEST(s21_insert_test4) {
  const char *source = "Hello!";
  const char *insertion = "";
  char *result = s21_insert(source, insertion, 5);
  ck_assert_str_eq(result, "Hello!");
  free(result);
}
END_TEST

START_TEST(s21_insert_test5) {
  const char *source = "";
  const char *insertion = "123";
  char *result = s21_insert(source, insertion, 0);
  ck_assert_str_eq(result, "123");
  free(result);
}
END_TEST

START_TEST(s21_insert_test6) {
  const char *insertion = "123";
  char *result = s21_insert(NULL, insertion, 0);
  ck_assert_pstr_eq(result, NULL);
}
END_TEST

START_TEST(s21_insert_test7) {
  const char *source = "Hello!";
  char *result = s21_insert(source, NULL, 5);
  ck_assert_str_eq(result, "Hello!");
  free(result);
}
END_TEST

START_TEST(s21_memchr_test1) {
  const char str1[] = "Hello, World!";
  const char ch_exist = 'o';
  char *result;
  char *expected;
  result = memchr(str1, ch_exist, sizeof(str1));
  expected = s21_memchr(str1, ch_exist, sizeof(str1));
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_memchr_test2) {
  const char str1[] = "Hello, World!";
  const char ch_not_exist = 'z';
  char *result;
  char *expected;
  result = memchr(str1, ch_not_exist, sizeof(str1));
  expected = s21_memchr(str1, ch_not_exist, sizeof(str1));
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_memchr_test3) {
  const char ch_exist = 'o';
  char *result;
  char *expected;
  result = memchr("", ch_exist, 0);
  expected = s21_memchr("", ch_exist, 0);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_memchr_test4) {
  const char str1[] = "Hello, World!";
  const char ch_exist = 'o';
  char *result;
  char *expected;
  result = memchr(str1, ch_exist, 5);
  expected = s21_memchr(str1, ch_exist, 5);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_memchr_test5) {
  const char str2[] =
      "What you are referring to as Linux is in fact GNU/Linux or as recently "
      "i "
      "have taken to calling - GNU+Linux. Linux is not an operating system "
      "unto "
      "itself but rather another free component of a full functioning GNU "
      "system "
      "made useful by the GNU corelibs, shell utilities and vital system "
      "components comprising a full OS as defined by POSIX.";
  const char ch_large_string = 'r';
  char *result;
  char *expected;
  result = memchr(str2, ch_large_string, sizeof(str2));
  expected = s21_memchr(str2, ch_large_string, sizeof(str2));
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_memcmp_test1) {
  unsigned char src[15] = "1234567890";
  unsigned char dst[15] = "1234567890";
  int result = s21_memcmp(src, dst, 10);
  int expected = memcmp(src, dst, 10);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test2) {
  unsigned char src[15] = "1234567890";
  unsigned char dst[15] = "7234567890";
  int result = s21_memcmp(src, dst, 10);
  int expected = memcmp(src, dst, 10);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test3) {
  const char *str1 = "Hello, world!Hello, world!";
  const char *str2 = "Hello, world!Hello, world!";
  s21_size_t n = 10;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test4) {
  const char *str1 = "Hello, world!";
  const char *str2 = "Hello, world!";
  s21_size_t n = 4;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test5) {
  const char *str1 = "test";
  const char *str2 = "ttest";
  s21_size_t n = 0;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test6) {
  const char *str1 = "";
  const char *str2 = "";
  s21_size_t n = 0;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test7) {
  const char *str1 = "";
  const char *str2 = "";
  s21_size_t n = 1;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcmp_test8) {
  const char *str1 = "Hello";
  const char *str2 = "HelIo";
  s21_size_t n = 5;
  int result = s21_memcmp(str1, str2, n);
  int expected = memcmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_memcpy_test1) {
  const char original[] = "Hello, World!";
  char result_orig[15];
  char result[15];
  memcpy(result_orig, original, sizeof(original));
  s21_memcpy(result, original, sizeof(original));
  ck_assert_mem_eq(result_orig, result, sizeof(original));
}
END_TEST

START_TEST(s21_memcpy_test2) {
  const size_t size = 10000;
  char *original_large = malloc(size);
  char *result_orig_large = malloc(size);
  char *result_large = malloc(size);
  for (size_t i = 0; i < size; i++) {
    original_large[i] = (char)(i % 256);
  }
  memcpy(result_orig_large, original_large, size);
  s21_memcpy(result_large, original_large, size);
  ck_assert_mem_eq(result_orig_large, result_large, size);
  free(original_large);
  free(result_orig_large);
  free(result_large);
}
END_TEST

START_TEST(s21_memcpy_test3) {
  char result_orig_n[15];
  char result_n[15];
  char *empty_string = NULL;
  size_t length = empty_string ? strlen(empty_string) : 0;
  memcpy(result_orig_n, empty_string, length);
  s21_memcpy(result_n, empty_string, length);
  ck_assert_mem_eq(result_orig_n, result_n, length);
}
END_TEST

START_TEST(s21_memcpy_test4) {
  char original[] = "Hello, World!";
  char result[15] = {0};
  char result_orig[15] = {0};
  size_t length = strlen(original);
  s21_memcpy(result, original, length + 1);
  memcpy(result_orig, original, length + 1);
  ck_assert_str_eq(result_orig, result);
}
END_TEST

START_TEST(s21_memset_test1) {
  char result[] = "Hello, World!";
  char result_orig[] = "Hello, World!";
  int ch = ' ';
  size_t n = strlen(result);
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_memset_test2) {
  char result[] = "Hello";
  char result_orig[] = "Hello";
  int ch = '\0';
  size_t n = 4;
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_memset_test3) {
  char result[] = "Hello, World!";
  char result_orig[] = "Hello, World!";
  int ch = ' ';
  size_t n = 5;
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_memset_test4) {
  char result[] = "Hello, World!";
  char result_orig[] = "Hello, World!";
  int ch = ' ';
  size_t n = 0;
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_memset_test5) {
  char result[] = "";
  char result_orig[] = "";
  int ch = '\0';
  size_t n = 0;
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_memset_test6) {
  char result[] = "Hello";
  char result_orig[] = "Hello";
  int ch = '\0';
  size_t n = 4;
  ck_assert_str_eq(memset(result, ch, n), s21_memset(result_orig, ch, n));
}
END_TEST

START_TEST(s21_sprintf_test1) {
  char buffer_1[200], buffer_2[200];
  char sym_1 = 'K', sym_2 = '\t', sym_3 = '\\';
  char *format = "sym_1 = %c, sym_2 = %c, sym_3 = %-5c, %% = %%";
  sprintf(buffer_1, format, sym_1, sym_2, sym_3);
  s21_sprintf(buffer_2, format, sym_1, sym_2, sym_3);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_sprintf_test2) {
  char buffer_1[300], buffer_2[300];
  char str_1[] = "Hello, world!", str_2[] = "\tline 1\n\tline 2";
  char *format =
      "first 8 symbols from str_1 = \"%80s\", full str_2 = \"%s\", null but "
      "not "
      "enough width = %*s";
  sprintf(buffer_1, format, str_1, str_2, 1, NULL);
  s21_sprintf(buffer_2, format, str_1, str_2, 1, NULL);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_sprintf_test3) {
  char buffer_1[300], buffer_2[300];
  short short_1 = 31337, short_2 = 0, short_3 = -3556;
  int int_1 = 7354354, int_2 = 0, int_3 = -9;
  long long_1 = 3834394354346l, long_2 = 0l, long_3 = -43835435438341l;
  char *format =
      "SHORT 1-3: %hd %-.3hd %+hd\nINT 1-3: %-15d %d %+15d\nLONG 1-3: %025ld "
      "%50.40ld % ld";
  sprintf(buffer_1, format, short_1, short_2, short_3, int_1, int_2, int_3,
          long_1, long_2, long_3);
  s21_sprintf(buffer_2, format, short_1, short_2, short_3, int_1, int_2, int_3,
              long_1, long_2, long_3);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_sprintf_test4) {
  char buffer_1[300], buffer_2[300];
  short unsigned int suint_1 = 69, suint_2 = 0;
  unsigned int uint_1 = 0xABCDEFu, uint_2 = 0u;
  long unsigned int ulint_1 = 0x1F82C716Bul, ulint_2 = 0ul;
  char *format =
      "SUINT: %#10ho %hX UINT: %.15u %u UINT64: %*lu %020lu\nOCTAL: %*o %#-2lo "
      "HEX: %#x % 20lX %#lX";
  sprintf(buffer_1, format, suint_1, suint_2, uint_1, uint_2, 20, ulint_1,
          ulint_2, -10, uint_1, ulint_1, uint_1, ulint_1, ulint_1);
  s21_sprintf(buffer_2, format, suint_1, suint_2, uint_1, uint_2, 20, ulint_1,
              ulint_2, -10, uint_1, ulint_1, uint_1, ulint_1, ulint_1);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_sprintf_test5) {
  char buffer_1[300], buffer_2[300];
  int int_1 = 7354354;
  char str_1[] = "Hello, world!";
  char *format = "&int1 = %p, NULL = %p, &str1 = %p";
  sprintf(buffer_1, format, &int_1, NULL, str_1);
  s21_sprintf(buffer_2, format, &int_1, NULL, str_1);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_sprintf_test6) {
  char buffer_1[300], buffer_2[300];
  int printed_1, printed_2;
  long printed_3, printed_4;
  short printed_5, printed_6;
  char *format = "Hello%n, world%ln!%hn";
  sprintf(buffer_1, format, &printed_1, &printed_3, &printed_5);
  s21_sprintf(buffer_2, format, &printed_2, &printed_4, &printed_6);
  ck_assert_str_eq(buffer_1, buffer_2);
  ck_assert_int_eq(printed_1, printed_2);
  ck_assert_int_eq(printed_3, printed_4);
  ck_assert_int_eq(printed_5, printed_6);
}
END_TEST

START_TEST(s21_sprintf_test7) {
  char str1[1000];
  char str2[1000];
  int r1 =
      sprintf(str1,
              "[%+-10.3f][%+10.2f][%15.10f][%+*.6f][%*.10f][%-10.*f][%25.*f]"
              "[%25.f][%#+10.f][%*.*f]",
              2546.4324, 3452.4325, 5678.43256, 25, 456789.243242, 10,
              3456789123.43245, 2, 12345.6788, 1, 34.4325432, 4325678.43242,
              34567.2345432, 10, 2, 34567.43244);
  int r2 = s21_sprintf(str2,
                       "[%+-10.3f][%+10.2f][%15.10f][%+*.6f][%*.10f][%-10.*f][%"
                       "25.*f][%25.f][%#+10.f][%*.*f]",
                       2546.4324, 3452.4325, 5678.43256, 25, 456789.243242, 10,
                       3456789123.43245, 2, 12345.6788, 1, 34.4325432,
                       4325678.43242, 34567.2345432, 10, 2, 34567.43244);
  ck_assert_str_eq(str1, str2);
  ck_assert_int_eq(r1, r2);
}
END_TEST

START_TEST(s21_sprintf_test8) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10o testtext %-.8o testtext %-7o TESTTEXT %-.o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test9) {
  char str1[100];
  char str2[100];
  char *str3 = "%c abc %c abc %c abc %c abc %c";
  int a = 9;
  int b = 10;
  int c = 17;
  int d = 66;
  int e = 124;
  ck_assert_int_eq(sprintf(str1, str3, a, b, c, d, e),
                   s21_sprintf(str2, str3, a, b, c, d, e));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test10) {
  char str1[100];
  char str2[100];
  char *str3 = "%c abc %c abc %c abc %c abc %c";
  int a = -6;
  int b = -10;
  int c = -17;
  int d = -66;
  int e = -124;
  ck_assert_int_eq(sprintf(str1, str3, a, b, c, d, e),
                   s21_sprintf(str2, str3, a, b, c, d, e));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test11) {
  char str1[100];
  char str2[100];
  char *str3 = "%c abc %c abc %c abc %c abc %c";
  int a = 60;
  int b = 50;
  int c = 1744;
  int d = 386;
  int e = 257;
  ck_assert_int_eq(sprintf(str1, str3, a, b, c, d, e),
                   s21_sprintf(str2, str3, a, b, c, d, e));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test12) {
  char str1[100];
  char str2[100];
  char *str3 = "%c abc %c abc %c abc %c abc %c";
  char a = 0;
  ck_assert_int_eq(sprintf(str1, str3, a, a, a, a, a),
                   s21_sprintf(str2, str3, a, a, a, a, a));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test13) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "{%6.4c}{%-6.4c}{%4.10lc}{%-4.10lc}{%-0lc}";
  int a = 10;
  unsigned long int b = 10;
  unsigned long int c = 10;
  ck_assert_int_eq(sprintf(str1, str3, a, a, b, c, c),
                   s21_sprintf(str2, str3, a, a, b, c, c));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test14) {
  char str1[100];
  char str2[100];
  char *str3 = "%-010c abc % -10c abc %-lc";
  int a = 74;
  unsigned long int b = 74;
  ck_assert_int_eq(sprintf(str1, str3, a, a, b),
                   s21_sprintf(str2, str3, a, a, b));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test15) {
  char str1[100];
  char str2[100];
  char *str3 = "%+010.5c abc % +10.5c abc %-10lc abc %-10lc abc %+10lc";
  char a = 92;
  unsigned long int b = 92;
  unsigned long int c = 92;
  ck_assert_int_eq(sprintf(str1, str3, a, a, b, c, c),
                   s21_sprintf(str2, str3, a, a, b, c, c));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test16) {
  char str1[100];
  char str2[100];
  char *str3 = "%6.4c abc %-6.4c abc %4.10lc abc %-4.10lc abc %-0lc";
  int a = 10;
  unsigned long int b = 10;
  unsigned long int c = 10;
  ck_assert_int_eq(sprintf(str1, str3, a, a, b, c, c),
                   s21_sprintf(str2, str3, a, a, b, c, c));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test17) {
  char str1[100];
  char str2[100];
  char *str3 = "%6.4c abc %-6.4c abc %4.10lc abc %-4.10lc abc %-0lc";
  int a = -10;
  unsigned long int b = 10;
  unsigned long int c = 10;
  ck_assert_int_eq(sprintf(str1, str3, a, a, b, c, c),
                   s21_sprintf(str2, str3, a, a, b, c, c));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test18) {
  char str1[100];
  char str2[100];
  char *str3 = "%#c abc %#c abc %#c abc %#c abc %#c";
  ck_assert_int_eq(sprintf(str1, str3, ' ', 'n', '5', '%', '\\'),
                   s21_sprintf(str2, str3, ' ', 'n', '5', '%', '\\'));
  ck_assert_pstr_eq(str1, str2);

  // %d
}
END_TEST

START_TEST(s21_sprintf_test19) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "abc %d abc";
  int val = -12;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test20) {
  char str1[100];
  char str2[100];
  char *str3 = "%d abc %d abc %d";
  int val = 012;
  int val2 = -017;
  int val3 = 07464;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test21) {
  char str1[100];
  char str2[100];
  char *str3 = "%d abc %d abc %d";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test22) {
  char str1[100];
  char str2[100];
  char *str3 = "%ld abc %ld abc %hd TESTTEXT %hd";
  long int val = 3088675747373646;
  long val2 = 33030030303;
  short int val3 = 22600;
  short val4 = -120;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test23) {
  char str1[100];
  char str2[100];
  char *str3 = "%3d abc %5d abc %10d";
  int val = -3015;
  int val2 = -11234;
  int val3 = -99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test24) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5d abc %.23d abc %3.d TESTTEXT %.d %.6d";
  int val = -3015;
  int val2 = -712;
  int val3 = -99;
  int val4 = -38;
  int val5 = -100;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test25) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5d abc %-.8d abc %-7d TESTTEXT %-.d";
  int val = -3015;
  int val2 = -712;
  int val3 = -99;
  int val4 = -2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test26) {
  char str1[200];
  char str2[200];
  char *str3 = "%0d abc %0.d abc %0.0d TESTTEXT %0d TESTTEXT %.d";
  int val = -3015;
  int val2 = -712;
  int val3 = -99;
  int val4 = -2939;
  int val5 = -0123;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test27) {
  char str1[200];
  char str2[200];
  char *str3 = "%+d abc %+3.d abc %+5.7d TESTTEXT %+10i";
  int val = -3015;
  int val2 = -712;
  int val3 = -99;
  int val4 = -2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test28) {
  char str1[200];
  char str2[200];
  char *str3 = "%d abc %3.d abc %5.7d TESTTEXT %10d %#d %-i %+d %.d % .d";
  int val = 0;
  ck_assert_int_eq(
      sprintf(str1, str3, val, val, val, val, val, val, val, val, val),
      s21_sprintf(str2, str3, val, val, val, val, val, val, val, val, val,
                  val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test29) {
  char str1[200];
  char str2[200];
  char *str3 = "% d abc % 3.i abc % 5.7d TESTTEXT % 10d TESTTEXT %.d";
  int val = -32;
  int val2 = -8899;
  int val3 = -91918;
  int val4 = -32311;
  int val5 = -23;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test30) {
  char str1[200];
  char str2[200];
  char *str3 = "%+d abc %+3.i abc %+5.7d TESTTEXT %+10d TESTTEXT %+.d";
  int val = -32;
  int val2 = -8899;
  int val3 = 91918;
  int val4 = -32311;
  int val5 = 3261;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test31) {
  char str1[200];
  char str2[200];
  char *str3 = "%#d abc %#3d abc %#5.7i TESTTEXT %#.7d abc %#.d";
  int val = -32;
  int val2 = 8899;
  int val3 = -91918;
  int val4 = 32311;
  int val5 = -8894;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test32) {
  char str1[200];
  char str2[200];
  char *str3 = "%0d abc %06d abc %05.7i TESTTEXT %0.7d abc %0.d";
  int val = -32;
  int val2 = 8899;
  int val3 = -91918;
  int val4 = -32311;
  int val5 = -8894;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test33) {
  char str1[200];
  char str2[200];
  char *str3 = "%*d abc %-*d abc %*.*i TESTTEXT %.*d";
  int val = 32;
  int val2 = 8899;
  int val3 = -919;
  int val4 = 32311;
  int ast = 2;
  int ast2 = 5;
  int ast3 = 4;
  int ast4 = 10;
  int ast5 = 7;
  ck_assert_int_eq(
      sprintf(str1, str3, ast, val, ast2, val2, ast3, ast4, val3, ast5, val4),
      s21_sprintf(str2, str3, ast, val, ast2, val2, ast3, ast4, val3, ast5,
                  val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test34) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "%d";
  int val = 12;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test35) {
  char str1[1024] = "";
  char str2[1024] = "";
  int val = -75;
  sprintf(str1, "Hello %d %023d", val, val);
  s21_sprintf(str2, "Hello %d %023d", val, val);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test36) {
  char str1[200];
  char str2[200];
  char *str3 = "%- d abc %- 15d abc %- 15d abc %- d";
  int val = -3231;
  int val2 = -3231;
  int val3 = 3231;
  int val4 = 3231;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);

  // %e
}
END_TEST

START_TEST(s21_sprintf_test37) {
  char str1[100];
  char str2[100];
  char *str3 = "%e Abc %5e Abc %5.e";
  double num = -764231539.;
  ck_assert_int_eq(sprintf(str1, str3, num, num, num),
                   s21_sprintf(str2, str3, num, num, num));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test38) {
  char str1[300] = "";
  char str2[300] = "";
  double num1 = .3529373967;
  double num2 = .0003529373967;
  double num3 = 0.00000003529373967;
  char *str3 = "{% 30.1E}{% 30.E}{%030.0E}";
  ck_assert_int_eq(sprintf(str1, str3, num1, num2, num3),
                   s21_sprintf(str2, str3, num1, num2, num3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test39) {
  char str1[300];
  char str2[300];
  char *str3 = "randomtext %020e\nmoregarbage %020.e";
  double num = -5921563224775967.;
  ck_assert_int_eq(sprintf(str1, str3, num, num),
                   s21_sprintf(str2, str3, num, num));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test40) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "{%#e}{%#.e}{%#5.e}{%#.0e}{%#0.0e} %%";
  double num = -665695342471359.;
  ck_assert_int_eq(sprintf(str1, str3, num, num, num, num, num),
                   s21_sprintf(str2, str3, num, num, num, num, num));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test41) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "{%#e}{%#.e}{%#5.e}{%#.0e}{%#0.0e} %%";
  double num = 6.65695349e150;
  ck_assert_int_eq(sprintf(str1, str3, num, num, num, num, num),
                   s21_sprintf(str2, str3, num, num, num, num, num));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test42) {
  char str1[400] = "";
  char str2[400] = "";
  char *str3 = "{%Lf}{%.Lf}{%+-#Lf}{%+#.Lf}{%-#.Lf}";
  long double num = 76.756589;
  ck_assert_int_eq(sprintf(str1, str3, num, num, num, num, num),
                   s21_sprintf(str2, str3, num, num, num, num, num));
  ck_assert_pstr_eq(str1, str2);

  // %g
}
END_TEST

START_TEST(s21_sprintf_test43) {
  char str1[200] = "";
  char str2[200] = "";
  char *str3 = "{%g}{%.0g}{%4.2g}{%4.g}{%5.10g}";
  double num = -57251397732103429.56589367;
  ck_assert_int_eq(sprintf(str1, str3, num, num, num, num, num),
                   s21_sprintf(str2, str3, num, num, num, num, num));
  ck_assert_pstr_eq(str1, str2);

  // %x
}
END_TEST

START_TEST(s21_sprintf_test44) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "testtext %x testtext";
  int val = 0x32;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test45) {
  char str1[100];
  char str2[100];
  char *str3 = "%x testtext %x testtext %X";
  int val = 0x7a4;
  int val2 = 0x91ba123f;
  int val3 = 0x3123;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test46) {
  char str1[100];
  char str2[100];
  char *str3 = "%x testtext %x testtext %X";
  int val = 0x3015;
  int val2 = 0x712;
  int val3 = 0x99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test47) {
  char str1[100];
  char str2[100];
  char *str3 = "%lx testtext %lx testtext %hX %hx";
  long int val = 3088675747373646;
  long val2 = 33030030303;
  unsigned short int val3 = 22600;
  unsigned short val4 = 120;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test48) {
  char str1[100];
  char str2[100];
  char *str3 = "%3x testtext %5x testtext %10X";
  int val = 3015;
  int val2 = 01234;
  int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test49) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5x testtext %.23X testtext %3.x TESTTEXT %.x";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 38;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test50) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5x testtext %-.8X testtext %-7x TESTTEXT %-.x";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test51) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.25x testtext %15.28X testtext %-7x TESTTEXT %-.x";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test52) {
  char str1[200];
  char str2[200];
  char *str3 = "%0x testtext %0.x testtext %0.0X TESTTEXT %0x TESTTEXT %.x";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  int val5 = 0123;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test53) {
  char str1[200];
  char str2[200];
  char *str3 = "%+x testtext %+3.x testtext %+5.7x TESTTEXT %+10X";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test54) {
  char str1[200];
  char str2[200];
  char *str3 =
      "%x testtext %3.x testtext %5.7X TESTTEXT %10x %#x %-x %+x %.x % .x";
  int val = 0;
  ck_assert_int_eq(
      sprintf(str1, str3, val, val, val, val, val, val, val, val, val),
      s21_sprintf(str2, str3, val, val, val, val, val, val, val, val, val));
  ck_assert_pstr_eq(str1, str2);

  // %n
}
END_TEST

START_TEST(s21_sprintf_test55) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "asdfasft %n asdf";
  int valn1 = 0, valn2 = 0;
  ck_assert_int_eq(sprintf(str1, str3, &valn1),
                   s21_sprintf(str2, str3, &valn2));
  ck_assert_pstr_eq(str1, str2);
  ck_assert_int_eq(valn1, valn2);
}
END_TEST

START_TEST(s21_sprintf_test56) {
  char str1[100];
  char str2[100];
  char *str3 = "Tasd %o as%nqwe %o%n";
  int val = 012;
  int val2 = 017;
  int valn1 = 0, valn2 = 0, valn3 = 0, valn4 = 0;
  ck_assert_int_eq(sprintf(str1, str3, val, &valn1, val2, &valn3),
                   s21_sprintf(str2, str3, val, &valn2, val2, &valn4));
  ck_assert_pstr_eq(str1, str2);
  ck_assert_int_eq(valn1, valn2);
  ck_assert_int_eq(valn3, valn4);

  // %o
}
END_TEST

START_TEST(s21_sprintf_test57) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "testtext %o testtext";
  int val = 012;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test58) {
  char str1[100];
  char str2[100];
  char *str3 = "%o testtext %o testtext %o";
  int val = 012;
  int val2 = 017;
  int val3 = 07464;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test59) {
  char str1[100];
  char str2[100];
  char *str3 = "%o testtext %o testtext %o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test60) {
  char str1[100];
  char str2[100];
  char *str3 = "%lo testtext %lo testtext %ho TESTTEXT %ho";
  long int val = 3088675747373646;
  unsigned long int val2 = 33030030303;
  unsigned short int val3 = 22600;
  unsigned short val4 = 120;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test61) {
  char str1[100];
  char str2[100];
  char *str3 = "%3o testtext %5o testtext %10o";
  int val = 3015;
  int val2 = 01234;
  int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test62) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5o testtext %.23o testtext %3.o TESTTEXT %.o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 38;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test63) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5o testtext %-.8o testtext %-7o TESTTEXT %-.o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test64) {
  char str1[200];
  char str2[200];
  char *str3 = "%0o testtext %0.o testtext %0.0o TESTTEXT %0o TESTTEXT %.o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  int val5 = 0123;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test65) {
  char str1[200];
  char str2[200];
  char *str3 = "%+o testtext %+3.o testtext %+5.7o TESTTEXT %+10o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test66) {
  char str1[200];
  char str2[200];
  char *str3 =
      "%o testtext %3.o testtext %5.7o TESTTEXT %10o %#o %-o %+o %.o % .o";
  int val = 0;
  ck_assert_int_eq(
      sprintf(str1, str3, val, val, val, val, val, val, val, val, val),
      s21_sprintf(str2, str3, val, val, val, val, val, val, val, val, val));
  ck_assert_pstr_eq(str1, str2);

  // %%
}
END_TEST

START_TEST(s21_sprintf_test67) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "%%TESTTEXT %o TESTTEXT";
  int val = 012;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test68) {
  char str1[100];
  char str2[100];
  char *str3 = "TESTTEXT %o 123%%%%asfd %o";
  int val = 012;
  int val2 = 017;
  ck_assert_int_eq(sprintf(str1, str3, val, val2),
                   s21_sprintf(str2, str3, val, val2));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test69) {
  char str1[100];
  char str2[100];
  char *str3 = "%o Tasdfe%%asf %o TESTTEXT %o";
  int val = 3015;
  int val2 = 712;
  int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);

  // %p
}
END_TEST

START_TEST(s21_sprintf_test70) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "testtext %p testtext";
  char *val = "0p32";
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test71) {
  char str1[100];
  char str2[100];
  char *str3 = "%p testtext %p testtext %p";
  char *val = "0p7a4";
  char *val2 = "0p91ba123f";
  char *val3 = "0p3123";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test72) {
  char str1[100];
  char str2[100];
  char *str3 = "%p testtext %p testtext %p";
  char *val = "0p3015";
  char *val2 = "0p712";
  char *val3 = "0p99";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test73) {
  char str1[100];
  char str2[100];
  char *str3 = "%p testtext %p testtext %p TESTTEXT %p";
  long int *val = (void *)3088675747373646;
  long long int *val2 = (void *)33030030303;
  unsigned short int *val3 = (void *)22600;
  unsigned char *val4 = (void *)120;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test74) {
  char str1[100];
  char str2[100];
  char *str3 = "%3p testtext %5p testtext %12p";
  char *val = "1000";
  char *val2 = "01234567";
  char *val3 = "899";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test75) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5p testtext %.23p testtext %3.p TESTTEXT %.p";
  char *val = "1000";
  char *val2 = "01234567";
  char *val3 = "899";
  char *val4 = "38123";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test76) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5p testtext %-.4p testtext %-16p TESTTEXT %-.5p";
  char *val = "1000";
  char *val2 = "01234567";
  char *val3 = "899";
  char *val4 = "38123";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test77) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.15p testtext %15.24p testtext %16p TESTTEXT %-.5p";
  char *val = "1000";
  char *val2 = "01234567";
  char *val3 = "899";
  char *val4 = "38123";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test78) {
  char str1[200];
  char str2[200];
  char *str3 = "%0p testtext %0.p testtext %0.0p TESTTEXT %0p TESTTEXT %.p";
  char *val = "1000";
  char *val2 = "01234567";
  char *val3 = "899";
  char *val4 = "38123";
  char *val5 = "0123";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test79) {
  char str1[200] = "";
  char str2[200] = "";
  char *str3 = "{%0p}{%06p}{%05.7p}{%0.7p abc %0.p}";
  char *val = "32";
  char *val2 = "8899";
  char *val3 = "91918";
  char *val4 = "32311";
  char *val5 = "8894";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);

  // %s
}
END_TEST

START_TEST(s21_sprintf_test80) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "testtext %s testtext";
  char *val = "Hello, world!";
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test81) {
  char str1[100];
  char str2[100];
  char *str3 = "%s testtext %s testtext %s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test82) {
  char str1[100];
  char str2[100];
  char *str3 = "%s testtext %s testtext %s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test83) {
  char str1[280] = "";
  char str2[280] = "";
  char *str3 = "{% s}{% 3.s}{% 5.7s}{% 10s TESTTEXT %.s}";
  char *val = "You spin me right round, ";
  char *val2 = "baby, right round";
  char *val3 = "Like a record, baby, right ";
  char *val4 = "round round round";
  char *val5 = "I want your love";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test84) {
  char str1[200];
  char str2[200];
  char *str3 = "%3s testtext %5s testtext %10s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test85) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5s testtext %.23s testtext %3.s TESTTEXT %.s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  char *val4 = "anothertestphrase anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test86) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5s testtext %-.8s testtext %-7s TESTTEXT %-.s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  char *val4 = "anothertestphrase anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test87) {
  char str1[200];
  char str2[200];
  char *str3 = "%0s testtext %0.s testtext %0.0s TESTTEXT %0s TESTTEXT %.s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  char *val4 = "anothertestphrase anothertestphrase";
  char *val5 = "anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test88) {
  char str1[200];
  char str2[200];
  char *str3 = "%+s testtext %+3.s testtext %5.7s TESTTEXT %10s";
  char *val = "Hello, world!";
  char *val2 = "testphrase";
  char *val3 = "anothertestphrase";
  char *val4 = "anothertestphrase anothertestphrase";
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);

  // %u
}
END_TEST

START_TEST(s21_sprintf_test89) {
  char str1[100] = "";
  char str2[100] = "";
  char *str3 = "testtext %u testtext";
  unsigned int val = 012;
  ck_assert_int_eq(sprintf(str1, str3, val), s21_sprintf(str2, str3, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test90) {
  char str1[100];
  char str2[100];
  char *str3 = "%u testtext %u testtext %u";
  unsigned int val = 012;
  unsigned int val2 = 017;
  unsigned int val3 = 07464;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test91) {
  char str1[100];
  char str2[100];
  char *str3 = "%u testtext %u testtext %u";
  unsigned int val = 3015;
  unsigned int val2 = 712;
  unsigned int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test92) {
  char str1[100];
  char str2[100];
  char *str3 = "%lu testtext %lu testtext %hu TESTTEXT %hu";
  long unsigned int val = 3088675747373646;
  long unsigned val2 = 33030030303;
  unsigned short val3 = 22600;
  unsigned short val4 = 120;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test93) {
  char str1[100];
  char str2[100];
  char *str3 = "%3u testtext %5u testtext %10u";
  unsigned int val = 3015;
  unsigned int val2 = 01234;
  unsigned int val3 = 99;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3),
                   s21_sprintf(str2, str3, val, val2, val3));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test94) {
  char str1[200];
  char str2[200];
  char *str3 = "%6.5u testtext %.23u testtext %3.u TESTTEXT %.u";
  unsigned int val = 3015;
  unsigned int val2 = 712;
  unsigned int val3 = 99;
  unsigned int val4 = 38;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test95) {
  char str1[200];
  char str2[200];
  char *str3 = "%-10.5u testtext %-.8u testtext %-7u TESTTEXT %-.u";
  unsigned int val = 3015;
  unsigned int val2 = 712;
  unsigned int val3 = 99;
  unsigned int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test96) {
  char str1[200];
  char str2[200];
  char *str3 = "%0u testtext %0.u testtext %0.0u TESTTEXT %0u TESTTEXT %.u";
  unsigned int val = 3015;
  unsigned int val2 = 712;
  unsigned int val3 = 99;
  unsigned int val4 = 2939;
  unsigned int val5 = 0123;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4, val5),
                   s21_sprintf(str2, str3, val, val2, val3, val4, val5));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test97) {
  char str1[200];
  char str2[200];
  char *str3 = "%+u testtext %+3.u testtext %+5.7u TESTTEXT %+10u";
  unsigned int val = 3015;
  unsigned int val2 = 712;
  unsigned int val3 = 99;
  unsigned int val4 = 2939;
  ck_assert_int_eq(sprintf(str1, str3, val, val2, val3, val4),
                   s21_sprintf(str2, str3, val, val2, val3, val4));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test98) {
  char str1[200];
  char str2[200];
  char *str3 =
      "%u testtext %3.u testtext %5.7u TESTTEXT %10u %#u %-u %+u %.u % .u";
  unsigned int val = 0;
  sprintf(str1, str3, val, val, val, val, val, val, val, val, val);
  s21_sprintf(str2, str3, val, val, val, val, val, val, val, val, val);
  ck_assert_int_eq(
      sprintf(str1, str3, val, val, val, val, val, val, val, val, val),
      s21_sprintf(str2, str3, val, val, val, val, val, val, val, val, val));
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test99) {
  char *s21_test_str = (char *)calloc(512, sizeof(char));
  char *lib_test_str = (char *)calloc(512, sizeof(char));
  int lib_res = sprintf(lib_test_str, "%c", '\0');
  int s21_res = s21_sprintf(s21_test_str, "%c", '\0');
  ck_assert_str_eq(s21_test_str, lib_test_str);
  ck_assert_int_eq(s21_res, lib_res);
  free(s21_test_str);
  free(lib_test_str);
}
END_TEST

START_TEST(s21_sprintf_test100) {
  char str1[200] = "";
  char str2[200] = "";
  char *str3 = "%#G %#.0g %020G %020.5g %.2f %.0f %.2e %.0e";
  float f1 = 5.0f;
  float f2 = 5.005f;
  float f3 = 9.999f;
  int res1 = sprintf(str1, str3, f1, f1, f1, f2, f3, f3, f3, f3);
  int res2 = s21_sprintf(str2, str3, f1, f1, f1, f2, f3, f3, f3, f3);
  ck_assert_int_eq(res1, res2);
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_sprintf_test101) {
  char str1[300] = "";
  char str2[300] = "";
  char *str3 = "%+050.25Lf";
  long double f1 = 9.9999999999e-20L;
  int res1 = sprintf(str1, str3, f1);
  int res2 = s21_sprintf(str2, str3, f1);
  ck_assert_int_eq(res1, res2);
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_strchr_test1) {
  const char *str1 = "Arrr hello, brave new world!";
  const int c = 'z';
  char *result = s21_strchr(str1, c);
  char *expected = strchr(str1, c);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strchr_test2) {
  const char *str3 = "";
  const int c = 'r';
  char *result = s21_strchr(str3, c);
  char *expected = strchr(str3, c);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strchr_test3) {
  const char *str4 = "Arrr hello, brave new world!";
  const int c = 'r';
  char *result = s21_strchr(str4, c);
  char *expected = strchr(str4, c);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strchr_test4) {
  const char *str2 = "///";
  const int c = ' ';
  char *result = s21_strchr(str2, c);
  char *expected = strchr(str2, c);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strcspn_test1) {
  const char *str = "Hello, world!";
  const char *reject = "Detox";
  s21_size_t result = s21_strcspn(str, reject);
  s21_size_t expected = strcspn(str, reject);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strcspn_test2) {
  const char *str = "abcdefghijk";
  const char *reject = "abcde";
  s21_size_t result = s21_strcspn(str, reject);
  s21_size_t expected = strcspn(str, reject);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strcspn_test3) {
  const char *str = "";
  const char *reject = "test";
  s21_size_t result = s21_strcspn(str, reject);
  s21_size_t expected = strcspn(str, reject);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strcspn_test4) {
  const char *str = "test";
  const char *reject = "";
  s21_size_t result = s21_strcspn(str, reject);
  s21_size_t expected = strcspn(str, reject);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strcspn_test5) {
  const char *str = "";
  const char *reject = "";
  s21_size_t result = s21_strcspn(str, reject);
  s21_size_t expected = strcspn(str, reject);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strerror_test1) {
  for (int i = 0; i < N; i++) {
    char *result = s21_strerror(i);
    char *expected = strerror(i);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strerror_test2) {
  char *result = s21_strerror(200);
  char *expected = strerror(200);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strlen_test1) {
  const char *strl = "Hello, world!";
  s21_size_t result = s21_strlen(strl);
  size_t expected = strlen(strl);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strlen_test2) {
  const char *strl = "";
  s21_size_t result = s21_strlen(strl);
  size_t expected = strlen(strl);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strlen_test3) {
  const char *strl =
      "What you are referring to as Linux is in fact GNU/Linux or as recently "
      "i "
      "have taken to calling - GNU+Linux.";
  s21_size_t result = s21_strlen(strl);
  size_t expected = strlen(strl);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strlen_test4) {
  const char *strl = "00";
  s21_size_t result = s21_strlen(strl);
  size_t expected = strlen(strl);
  ck_assert_int_eq(result, expected);
}
END_TEST

START_TEST(s21_strncat_test1) {
  char result[20] = "Hello, ";
  char expected[20] = "Hello, ";
  const char *src = "World!";
  s21_strncat(result, src, 3);
  strncat(expected, src, 3);
  ck_assert_str_eq(result, expected);
}
END_TEST

START_TEST(s21_strncat_test2) {
  char empty_result[20] = "";
  char empty_expected[20] = "";
  const char *message = "This is a long message";
  s21_strncat(empty_result, message, 10);
  strncat(empty_expected, message, 10);
  ck_assert_str_eq(empty_result, empty_expected);
}
END_TEST

START_TEST(s21_strncat_test3) {
  char result[20] = "Hello, ";
  char expected[20] = "Hello, ";
  s21_strncat(result, "", 5);
  strncat(expected, "", 5);
  ck_assert_str_eq(result, expected);
}
END_TEST

START_TEST(s21_strncmp_test1) {
  const char *str1 = "I'd like to interject for a moment.";
  const char *str2 = "What you are referring to as Linux is in fact GNU/Linux";
  s21_size_t n = 10;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncmp_test2) {
  const char *str1 = "I'd like to interject for a moment.";
  const char *str2 = "";
  s21_size_t n = 5;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncmp_test3) {
  const char *str1 = "What you are referring to";
  const char *str2 = "What you are referring to as Linux is in fact GNU/Linux";
  s21_size_t n = 4;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncmp_test4) {
  const char *str1 = "What you are referring to";
  const char *str2 = "wWhat you are referring to";
  s21_size_t n = 0;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncmp_test5) {
  const char *str1 = "";
  const char *str2 = "What you are referring to as Linux is in fact GNU/Linux";
  s21_size_t n = 0;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncmp_test6) {
  const char *str1 = ".";
  const char *str2 = "What you are referring to as Linux is in fact GNU/Linux";
  s21_size_t n = 1;
  int result = s21_strncmp(str1, str2, n);
  int expected = strncmp(str1, str2, n);
  ck_assert((result < 0 && expected < 0) || (result > 0 && expected > 0) ||
            (!result && !expected));
}
END_TEST

START_TEST(s21_strncpy_test1) {
  char result[20] = "Hello, world!";
  char expected[20] = "Hello, world!";
  char src[] = "Nice";
  s21_size_t n = 5;
  s21_strncpy(result, src, n);
  strncpy(expected, src, n);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strncpy_test2) {
  char empty_result[80] = "";
  char empty_expected[80] = "";
  const char *message = "String longer than length to copy";
  s21_strncpy(empty_result, message, 10);
  strncpy(empty_expected, message, 10);
  ck_assert_str_eq(empty_result, empty_expected);
}
END_TEST

START_TEST(s21_strncpy_test3) {
  char long_src[] = "Testtext";
  char long_result[50];
  char long_expected[50];
  s21_strncpy(long_result, long_src, 20);
  strncpy(long_expected, long_src, 20);
  ck_assert_str_eq(long_result, long_expected);
}
END_TEST

START_TEST(s21_strncpy_test4) {
  char result[20];
  char expected[20];
  const char *src = "Hello, World!";
  s21_strncpy(result, src, 20);
  strncpy(expected, src, 20);
  ck_assert_str_eq(result, expected);
}
END_TEST

START_TEST(s21_strncpy_test5) {
  char extended_result[50];
  char extended_expected[50];
  const char *src = "Hello, World!";
  s21_strncpy(extended_result, src, 50);
  strncpy(extended_expected, src, 50);
  ck_assert_str_eq(extended_result, extended_expected);
}
END_TEST

START_TEST(s21_strpbrk_test1) {
  const char *str = "Hello, brave new world!";
  const char *accept = "aiou";
  char *result = s21_strpbrk(str, accept);
  char *expected = strpbrk(str, accept);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_strpbrk_test2) {
  const char *accept = "z";
  const char *str = "Hello, brave new world!";
  char *result = s21_strpbrk(str, accept);
  char *expected = strpbrk(str, accept);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_strpbrk_test3) {
  const char *accept = " ";
  const char *str = "Hello, brave new world!";
  char *result = s21_strpbrk(str, accept);
  char *expected = strpbrk(str, accept);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_strpbrk_test4) {
  const char *accept = "1234567890";
  const char *str = "Hello, brave new world!";
  char *result = s21_strpbrk(str, accept);
  char *expected = strpbrk(str, accept);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_strpbrk_test5) {
  const char *accept = "?*!";
  const char *str = "Hello, brave new world!";
  char *result = s21_strpbrk(str, accept);
  char *expected = strpbrk(str, accept);
  ck_assert_ptr_eq(result, expected);
}
END_TEST

START_TEST(s21_strrchr_test1) {
  const char *result = s21_strrchr("Hello world", 'o');
  const char *expected = strrchr("Hello world", 'o');
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strrchr_test2) {
  const char *result = s21_strrchr("Hello, world!", 'z');
  const char *expected = strrchr("Hello, world!", 'z');
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strrchr_test3) {
  const char *result = s21_strrchr("", 'a');
  const char *expected = strrchr("", 'a');
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strrchr_test4) {
  const char *result = s21_strrchr("Hello, world!", 'H');
  const char *expected = strrchr("Hello, world!", 'H');
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strrchr_test5) {
  const char *result = s21_strrchr("Hello, world!Hello, world!", '!');
  const char *expected = strrchr("Hello, world!Hello, world!", '!');
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strstr_test1) {
  char *string = "What you are referring to as Linux is in fact GNU/Linux";
  char *substring = "GNU";
  char *expected = s21_strstr(string, substring);
  char *result = strstr(string, substring);
  ck_assert(expected == result);
}
END_TEST

START_TEST(s21_strstr_test2) {
  char *string = "What you are referring to as Linux is in fact GNU/Linux ";
  char *substring = "Linux";
  char *expected = s21_strstr(string, substring);
  char *result = strstr(string, substring);
  ck_assert(expected == result);
}
END_TEST

START_TEST(s21_strstr_test3) {
  char *string = "What you are referring to as Linux is in fact GNU/Linux ";
  char *substring = "What";
  char *expected = s21_strstr(string, substring);
  char *result = strstr(string, substring);
  ck_assert(expected == result);
}
END_TEST

START_TEST(s21_strstr_test4) {
  char *string = "What you are referring to as Linux is in fact GNU/Linux ";
  char *substring = "";
  char *expected = s21_strstr(string, substring);
  char *result = strstr(string, substring);
  ck_assert(expected == result);
}
END_TEST

START_TEST(s21_strstr_test5) {
  char *string = "What you are referring to as Linux is in fact GNU/Linux ";
  char *substring = "Windows";
  char *expected = s21_strstr(string, substring);
  char *result = strstr(string, substring);
  ck_assert(expected == result);
}
END_TEST

START_TEST(s21_strstr_test6) {
  const char *string = "";
  const char *substring = "Astra";
  const char *result = s21_strstr(string, substring);
  const char *expected = strstr(string, substring);
  ck_assert_pstr_eq(result, expected);
}
END_TEST

START_TEST(s21_strtok_test1) {
  char str1[] = "This is a test";
  char str2[] = "This is a test";
  char *result = s21_strtok(str1, " ");
  char *expected = strtok(str2, " ");
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, " ");
    expected = strtok(NULL, " ");
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strtok_test2) {
  char str1[] = "This, is, a, test";
  char str2[] = "This, is, a, test";
  const char *delim = ",";
  char *result = s21_strtok(str1, delim);
  char *expected = strtok(str2, delim);
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, delim);
    expected = strtok(NULL, delim);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strtok_test3) {
  char str1[] = "";
  char str2[] = "";
  const char *delim = ",";
  char *result = s21_strtok(str1, delim);
  char *expected = strtok(str2, delim);
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, delim);
    expected = strtok(NULL, delim);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strtok_test4) {
  char str1[] = "This,, is,,,a,,,,test";
  char str2[] = "This,, is,,,a,,,,test";
  const char *delim = ",";
  char *result = s21_strtok(str1, delim);
  char *expected = strtok(str2, delim);
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, delim);
    expected = strtok(NULL, delim);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strtok_test5) {
  char str1[] = "This is a test";
  char str2[] = "This is a test";
  const char *delim = ",";
  char *result = s21_strtok(str1, delim);
  char *expected = strtok(str2, delim);
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, delim);
    expected = strtok(NULL, delim);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_strtok_test6) {
  char str1[] = "T.hi s,, is,,,a,,,t.est.";
  char str2[] = "T.hi s,, is,,,a,,,t.est.";
  const char *delim = ", .";
  char *result = s21_strtok(str1, delim);
  char *expected = strtok(str2, delim);
  ck_assert_pstr_eq(result, expected);
  while (result != NULL && expected != NULL) {
    result = s21_strtok(NULL, delim);
    expected = strtok(NULL, delim);
    ck_assert_pstr_eq(result, expected);
  }
}
END_TEST

START_TEST(s21_to_lower_test1) {
  char str131[23] = "HELLO, WORLD!";
  char expected[23] = "hello, world!";
  char *dest1 = s21_to_lower(str131);
  ck_assert_str_eq(dest1, expected);
  free(dest1);
}
END_TEST

START_TEST(s21_to_lower_test2) {
  const char *input = "Hello, World!";
  char *result = s21_to_lower(input);
  size_t len = strlen(input) + 1;
  char *expected = malloc(len);
  strcpy(expected, input);
  char *ptr = expected;
  while (*ptr) {
    *ptr = tolower(*ptr);
    ptr++;
  }
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_lower_test3) {
  const char *input2 = "";
  char *result = s21_to_lower(input2);
  size_t len = strlen(input2) + 1;
  char *expected = malloc(len);
  strcpy(expected, input2);
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_lower_test4) {
  const char *input3 = "hello, world!";
  char *result = s21_to_lower(input3);
  size_t len = strlen(input3) + 1;
  char *expected = malloc(len);
  strcpy(expected, input3);
  char *ptr = expected;
  while (*ptr) {
    *ptr = tolower(*ptr);
    ptr++;
  }
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_lower_test5) {
  const char *input4 = "HELLO, WORLD!";
  char *result = s21_to_lower(input4);
  size_t len = strlen(input4) + 1;
  char *expected = malloc(len);
  strcpy(expected, input4);
  char *ptr = expected;
  while (*ptr) {
    *ptr = tolower(*ptr);
    ptr++;
  }
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_lower_test6) {
  const char *input5 = "HeLlO, WoRlD!";
  char *result = s21_to_lower(input5);
  size_t len = strlen(input5) + 1;
  char *expected = malloc(len);
  strcpy(expected, input5);
  char *ptr = expected;
  while (*ptr) {
    *ptr = tolower(*ptr);
    ptr++;
  }
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test1) {
  char str[23] = "hello, world!";
  char expected[23] = "HELLO, WORLD!";
  char *dest1 = s21_to_upper(str);
  ck_assert_str_eq(dest1, expected);
  free(dest1);
}
END_TEST

START_TEST(s21_to_upper_test2) {
  const char *input = "Hello, World!";
  char *result = s21_to_upper(input);
  size_t len = strlen(input) + 1;
  char *expected = malloc(len);
  strcpy(expected, input);
  char *ptr = expected;
  while (*ptr) {
    *ptr = toupper(*ptr);
    ptr++;
  }
  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test3) {
  const char *input2 = "";
  char *result = s21_to_upper(input2);
  size_t len = strlen(input2) + 1;
  char *expected = malloc(len);
  strcpy(expected, input2);

  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test4) {
  const char *input3 = "HELLO, WORLD!";
  char *result = s21_to_upper(input3);
  size_t len = strlen(input3) + 1;
  char *expected = malloc(len);
  strcpy(expected, input3);
  char *ptr = expected;

  while (*ptr) {
    *ptr = toupper(*ptr);
    ptr++;
  }

  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test5) {
  const char *input4 = "hello, world!";
  char *result = s21_to_upper(input4);
  size_t len = strlen(input4) + 1;
  char *expected = malloc(len);
  strcpy(expected, input4);
  char *ptr = expected;

  while (*ptr) {
    *ptr = toupper(*ptr);
    ptr++;
  }

  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test6) {
  const char *input5 = "HeLlO, WoRlD!";
  char *result = s21_to_upper(input5);
  size_t len = strlen(input5) + 1;
  char *expected = malloc(len);
  strcpy(expected, input5);
  char *ptr = expected;

  while (*ptr) {
    *ptr = toupper(*ptr);
    ptr++;
  }

  ck_assert_str_eq(result, expected);
  free(result);
  free(expected);
}
END_TEST

START_TEST(s21_to_upper_test7) {
  char *result = s21_to_upper(NULL);
  ck_assert_pstr_eq(result, NULL);
}
END_TEST

START_TEST(s21_trim_test1) {
  char str1[36] = "__Hello, world!__";
  char *trim1 = "_";
  char *dest = s21_trim(str1, trim1);
  ck_assert_str_eq(dest, "Hello, world!");
  free(dest);
}
END_TEST

START_TEST(s21_trim_test2) {
  char str2[53] = "\tHello, world! ";
  char *dest2 = s21_trim(str2, "");
  ck_assert_str_eq(dest2, "Hello, world!");
  free(dest2);
}
END_TEST

START_TEST(s21_trim_test3) {
  const char *original = "   Hello, world!   ";
  const char *trimmed_chars = " ";
  char *expected = "Hello, world!";
  char *result = s21_trim(original, trimmed_chars);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test4) {
  const char *original = "###Hello, world!###";
  const char *trimmed_chars = "#! ";
  char *expected = "Hello, world";
  char *result = s21_trim(original, trimmed_chars);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test5) {
  const char *original = ",,,Hello, world!!!,,,";
  const char *trimmed_chars = ",";
  char *expected = "Hello, world!!!";
  char *result = s21_trim(original, trimmed_chars);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test6) {
  const char *original = "123Hello, world!456";
  const char *trimmed_chars = "123456";
  char *expected = "Hello, world!";
  char *result = s21_trim(original, trimmed_chars);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test7) {
  const char *original = "Hello, world!";
  const char *trimmed_chars = "xyz";
  char *expected = "Hello, world!";
  char *result = s21_trim(original, trimmed_chars);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test8) {
  const char *trimmed_chars = "xyz";
  char *result = s21_trim(NULL, trimmed_chars);
  ck_assert_pstr_eq(result, NULL);
}
END_TEST

START_TEST(s21_trim_test9) {
  const char *original = " \t  Hello, world! \n  ";
  char *expected = "Hello, world!";
  char *result = s21_trim(original, NULL);
  ck_assert_str_eq(result, expected);
  free(result);
}
END_TEST

START_TEST(s21_trim_test10) {
  char *result = s21_trim(NULL, NULL);
  ck_assert_pstr_eq(result, NULL);
}
END_TEST

START_TEST(s21_no_valgrind_test1) {
  char buffer_1[300], buffer_2[300];
  float float_1 = 3.1415, float_2 = 0.0, float_3 = -0.0099, float_4 = 1.234E18;
  char *format =
      "float_1 = %.*f, float_2 = %.*f, float_3 = %f, float_4 = %.0f, inf = "
      "%+e, "
      "-INF = %e, #0 = %#.0f";
  sprintf(buffer_1, format, -5, float_1, 8, float_2, float_3, float_4,
          (float)(__DBL_MAX__ / __DBL_MIN__),
          (float)(-__DBL_MAX__ / __DBL_MIN__), 0.0);
  s21_sprintf(buffer_2, format, -5, float_1, 8, float_2, float_3, float_4,
              (float)(__DBL_MAX__ / __DBL_MIN__),
              (float)(-__DBL_MAX__ / __DBL_MIN__), 0.0);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_no_valgrind_test2) {
  char buffer_1[1000], buffer_2[1000];
  double double_1 = 2.31415926, double_2 = 0.0, double_3 = -1.234E-100,
         double_4 = 9.9999999999E128, double_5 = 999.999;
  char *format =
      "double_1 = %lf, double_2 = %lf, double_3 = %lf, double_4 = %lg, nan = "
      "%e, "
      "%%#.0G = %#.0lG, double_2 = %#lg, double_5 = %.0lg";
  sprintf(buffer_1, format, double_1, double_2, double_3, double_4, sqrt(-5.),
          double_1, double_2, double_5);
  s21_sprintf(buffer_2, format, double_1, double_2, double_3, double_4,
              sqrt(-5.), double_1, double_2, double_5);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_no_valgrind_test3) {
  char buffer_1[3000], buffer_2[3000];
  long double ldbl_1 = 1.23456789012345L, ldbl_2 = 0.0L,
              ldbl_3 = -3.1415926E-1000L, ldbl_4 = 3.1415926E+2500L,
              ldbl_5 = 100000.;
  char *format =
      "ldbl_1 = %.3Lf, ldbl_2 = %Lf, ldbl_3 = %Le, ldbl_4 = %#LG, ldbl_4 = "
      "%LE, "
      "%%.0Le = %.0Le, ldbl_5 = %g";
  sprintf(buffer_1, format, ldbl_1, ldbl_2, ldbl_3, ldbl_4, ldbl_4, ldbl_1,
          ldbl_5);
  s21_sprintf(buffer_2, format, ldbl_1, ldbl_2, ldbl_3, ldbl_4, ldbl_4, ldbl_1,
              ldbl_5);
  ck_assert_str_eq(buffer_1, buffer_2);
}
END_TEST

START_TEST(s21_no_valgrind_test4) {
  char s21_buffer2[256] = {0};
  char buffer2[256] = {0};
  s21_sprintf(s21_buffer2, "[%lf][%lf][%lf][%lf][%lf][%lf]", 0.0 / 0.0,
              1.0 / 0.0, 0.0 / 1.0, -0.0 / 0.0, -1.0 / 0.0, -0.0 / 1.0);
  sprintf(buffer2, "[%lf][%lf][%lf][%lf][%lf][%lf]", 0.0 / 0.0, 1.0 / 0.0,
          0.0 / 1.0, -0.0 / 0.0, -1.0 / 0.0, -0.0 / 1.0);
  ck_assert_str_eq(s21_buffer2, buffer2);
}
END_TEST

START_TEST(s21_no_valgrind_test5) {
  char str1[200] = "";
  char str2[200] = "";
  char *str3 = "%f %f %F %F %g %g %G %G %e %e %E %E";
  float f1 = INFINITY;
  float f2 = NAN;
  int res1 =
      sprintf(str1, str3, f1, f2, f1, f2, f1, f2, f1, f2, f1, f2, f1, f2);
  int res2 =
      s21_sprintf(str2, str3, f1, f2, f1, f2, f1, f2, f1, f2, f1, f2, f1, f2);
  ck_assert_int_eq(res1, res2);
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

START_TEST(s21_no_valgrind_test6) {
  char str1[300] = "";
  char str2[300] = "";
  char *str3 = "%#LG %#.0Lg %020LG %020.5Lg %.2Lf %.0Lf %.2Le % .0Le";
  long double f1 = 99999.9999999999L;
  int res1 = sprintf(str1, str3, f1, f1, f1, f1, f1, f1, f1, f1);
  int res2 = s21_sprintf(str2, str3, f1, f1, f1, f1, f1, f1, f1, f1);
  ck_assert_int_eq(res1, res2);
  ck_assert_pstr_eq(str1, str2);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("s21_insert_test");
  TCase *tc1_1 = tcase_create("s21_insert_test");
  Suite *s2 = suite_create("s21_memchr_test");
  TCase *tc2_1 = tcase_create("s21_memchr_test");
  Suite *s3 = suite_create("s21_memcmp_test");
  TCase *tc3_1 = tcase_create("s21_memcmp_test");
  Suite *s4 = suite_create("s21_memcpy_test");
  TCase *tc4_1 = tcase_create("s21_memcpy_test");
  Suite *s5 = suite_create("s21_memset_test");
  TCase *tc5_1 = tcase_create("s21_memset_test");
  Suite *s6 = suite_create("s21_sprintf_test");
  TCase *tc6_1 = tcase_create("s21_sprintf_test");
  Suite *s7 = suite_create("s21_strchr_test");
  TCase *tc7_1 = tcase_create("s21_strchr_test");
  Suite *s8 = suite_create("s21_strcspn_test");
  TCase *tc8_1 = tcase_create("s21_strcspn_test");
  Suite *s9 = suite_create("s21_strerror_test");
  TCase *tc9_1 = tcase_create("s21_strerror_test");
  Suite *s10 = suite_create("s21_strlen_test");
  TCase *tc10_1 = tcase_create("s21_strlen_test");
  Suite *s11 = suite_create("s21_strncat_test");
  TCase *tc11_1 = tcase_create("s21_strncat_test");
  Suite *s12 = suite_create("s21_strncmp_test");
  TCase *tc12_1 = tcase_create("s21_strncmp_test");
  Suite *s13 = suite_create("s21_strncpy_test");
  TCase *tc13_1 = tcase_create("s21_strncpy_test");
  Suite *s14 = suite_create("s21_strpbrk_test");
  TCase *tc14_1 = tcase_create("s21_strpbrk_test");
  Suite *s15 = suite_create("s21_strrchr_test");
  TCase *tc15_1 = tcase_create("s21_strrchr_test");
  Suite *s16 = suite_create("s21_strstr_test");
  TCase *tc16_1 = tcase_create("s21_strstr_test");
  Suite *s17 = suite_create("s21_strtok_test");
  TCase *tc17_1 = tcase_create("s21_strtok_test");
  Suite *s18 = suite_create("s21_to_lower_test");
  TCase *tc18_1 = tcase_create("s21_to_lower_test");
  Suite *s19 = suite_create("s21_to_upper_test");
  TCase *tc19_1 = tcase_create("s21_to_upper_test");
  Suite *s20 = suite_create("s21_trim_test");
  TCase *tc20_1 = tcase_create("s21_trim_test");
  Suite *s21 = suite_create("s21_no_valgrind_test");
  TCase *tc21_1 = tcase_create("s21_no_valgrind_test");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_insert_test1);
  tcase_add_test(tc1_1, s21_insert_test2);
  tcase_add_test(tc1_1, s21_insert_test3);
  tcase_add_test(tc1_1, s21_insert_test4);
  tcase_add_test(tc1_1, s21_insert_test5);
  tcase_add_test(tc1_1, s21_insert_test6);
  tcase_add_test(tc1_1, s21_insert_test7);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, s21_memchr_test1);
  tcase_add_test(tc2_1, s21_memchr_test2);
  tcase_add_test(tc2_1, s21_memchr_test3);
  tcase_add_test(tc2_1, s21_memchr_test4);
  tcase_add_test(tc2_1, s21_memchr_test5);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, s21_memcmp_test1);
  tcase_add_test(tc3_1, s21_memcmp_test2);
  tcase_add_test(tc3_1, s21_memcmp_test3);
  tcase_add_test(tc3_1, s21_memcmp_test4);
  tcase_add_test(tc3_1, s21_memcmp_test5);
  tcase_add_test(tc3_1, s21_memcmp_test6);
  tcase_add_test(tc3_1, s21_memcmp_test7);
  tcase_add_test(tc3_1, s21_memcmp_test8);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, s21_memcpy_test1);
  tcase_add_test(tc4_1, s21_memcpy_test2);
  tcase_add_test(tc4_1, s21_memcpy_test3);
  tcase_add_test(tc4_1, s21_memcpy_test4);
  suite_add_tcase(s5, tc5_1);
  tcase_add_test(tc5_1, s21_memset_test1);
  tcase_add_test(tc5_1, s21_memset_test2);
  tcase_add_test(tc5_1, s21_memset_test3);
  tcase_add_test(tc5_1, s21_memset_test4);
  tcase_add_test(tc5_1, s21_memset_test5);
  tcase_add_test(tc5_1, s21_memset_test6);
  suite_add_tcase(s6, tc6_1);
  tcase_add_test(tc6_1, s21_sprintf_test1);
  tcase_add_test(tc6_1, s21_sprintf_test2);
  tcase_add_test(tc6_1, s21_sprintf_test3);
  tcase_add_test(tc6_1, s21_sprintf_test4);
  tcase_add_test(tc6_1, s21_sprintf_test5);
  tcase_add_test(tc6_1, s21_sprintf_test6);
  tcase_add_test(tc6_1, s21_sprintf_test7);
  tcase_add_test(tc6_1, s21_sprintf_test8);
  tcase_add_test(tc6_1, s21_sprintf_test9);
  tcase_add_test(tc6_1, s21_sprintf_test10);
  tcase_add_test(tc6_1, s21_sprintf_test11);
  tcase_add_test(tc6_1, s21_sprintf_test12);
  tcase_add_test(tc6_1, s21_sprintf_test13);
  tcase_add_test(tc6_1, s21_sprintf_test14);
  tcase_add_test(tc6_1, s21_sprintf_test15);
  tcase_add_test(tc6_1, s21_sprintf_test16);
  tcase_add_test(tc6_1, s21_sprintf_test17);
  tcase_add_test(tc6_1, s21_sprintf_test18);
  tcase_add_test(tc6_1, s21_sprintf_test19);
  tcase_add_test(tc6_1, s21_sprintf_test20);
  tcase_add_test(tc6_1, s21_sprintf_test21);
  tcase_add_test(tc6_1, s21_sprintf_test22);
  tcase_add_test(tc6_1, s21_sprintf_test23);
  tcase_add_test(tc6_1, s21_sprintf_test24);
  tcase_add_test(tc6_1, s21_sprintf_test25);
  tcase_add_test(tc6_1, s21_sprintf_test26);
  tcase_add_test(tc6_1, s21_sprintf_test27);
  tcase_add_test(tc6_1, s21_sprintf_test28);
  tcase_add_test(tc6_1, s21_sprintf_test29);
  tcase_add_test(tc6_1, s21_sprintf_test30);
  tcase_add_test(tc6_1, s21_sprintf_test31);
  tcase_add_test(tc6_1, s21_sprintf_test32);
  tcase_add_test(tc6_1, s21_sprintf_test33);
  tcase_add_test(tc6_1, s21_sprintf_test34);
  tcase_add_test(tc6_1, s21_sprintf_test35);
  tcase_add_test(tc6_1, s21_sprintf_test36);
  tcase_add_test(tc6_1, s21_sprintf_test37);
  tcase_add_test(tc6_1, s21_sprintf_test38);
  tcase_add_test(tc6_1, s21_sprintf_test39);
  tcase_add_test(tc6_1, s21_sprintf_test40);
  tcase_add_test(tc6_1, s21_sprintf_test41);
  tcase_add_test(tc6_1, s21_sprintf_test42);
  tcase_add_test(tc6_1, s21_sprintf_test43);
  tcase_add_test(tc6_1, s21_sprintf_test44);
  tcase_add_test(tc6_1, s21_sprintf_test45);
  tcase_add_test(tc6_1, s21_sprintf_test46);
  tcase_add_test(tc6_1, s21_sprintf_test47);
  tcase_add_test(tc6_1, s21_sprintf_test48);
  tcase_add_test(tc6_1, s21_sprintf_test49);
  tcase_add_test(tc6_1, s21_sprintf_test50);
  tcase_add_test(tc6_1, s21_sprintf_test51);
  tcase_add_test(tc6_1, s21_sprintf_test52);
  tcase_add_test(tc6_1, s21_sprintf_test53);
  tcase_add_test(tc6_1, s21_sprintf_test54);
  tcase_add_test(tc6_1, s21_sprintf_test55);
  tcase_add_test(tc6_1, s21_sprintf_test56);
  tcase_add_test(tc6_1, s21_sprintf_test57);
  tcase_add_test(tc6_1, s21_sprintf_test58);
  tcase_add_test(tc6_1, s21_sprintf_test59);
  tcase_add_test(tc6_1, s21_sprintf_test60);
  tcase_add_test(tc6_1, s21_sprintf_test61);
  tcase_add_test(tc6_1, s21_sprintf_test62);
  tcase_add_test(tc6_1, s21_sprintf_test63);
  tcase_add_test(tc6_1, s21_sprintf_test64);
  tcase_add_test(tc6_1, s21_sprintf_test65);
  tcase_add_test(tc6_1, s21_sprintf_test66);
  tcase_add_test(tc6_1, s21_sprintf_test67);
  tcase_add_test(tc6_1, s21_sprintf_test68);
  tcase_add_test(tc6_1, s21_sprintf_test69);
  tcase_add_test(tc6_1, s21_sprintf_test70);
  tcase_add_test(tc6_1, s21_sprintf_test71);
  tcase_add_test(tc6_1, s21_sprintf_test72);
  tcase_add_test(tc6_1, s21_sprintf_test73);
  tcase_add_test(tc6_1, s21_sprintf_test74);
  tcase_add_test(tc6_1, s21_sprintf_test75);
  tcase_add_test(tc6_1, s21_sprintf_test76);
  tcase_add_test(tc6_1, s21_sprintf_test77);
  tcase_add_test(tc6_1, s21_sprintf_test78);
  tcase_add_test(tc6_1, s21_sprintf_test79);
  tcase_add_test(tc6_1, s21_sprintf_test80);
  tcase_add_test(tc6_1, s21_sprintf_test81);
  tcase_add_test(tc6_1, s21_sprintf_test82);
  tcase_add_test(tc6_1, s21_sprintf_test83);
  tcase_add_test(tc6_1, s21_sprintf_test84);
  tcase_add_test(tc6_1, s21_sprintf_test85);
  tcase_add_test(tc6_1, s21_sprintf_test86);
  tcase_add_test(tc6_1, s21_sprintf_test87);
  tcase_add_test(tc6_1, s21_sprintf_test88);
  tcase_add_test(tc6_1, s21_sprintf_test89);
  tcase_add_test(tc6_1, s21_sprintf_test90);
  tcase_add_test(tc6_1, s21_sprintf_test91);
  tcase_add_test(tc6_1, s21_sprintf_test92);
  tcase_add_test(tc6_1, s21_sprintf_test93);
  tcase_add_test(tc6_1, s21_sprintf_test94);
  tcase_add_test(tc6_1, s21_sprintf_test95);
  tcase_add_test(tc6_1, s21_sprintf_test96);
  tcase_add_test(tc6_1, s21_sprintf_test97);
  tcase_add_test(tc6_1, s21_sprintf_test98);
  tcase_add_test(tc6_1, s21_sprintf_test99);
  tcase_add_test(tc6_1, s21_sprintf_test100);
  tcase_add_test(tc6_1, s21_sprintf_test101);
  suite_add_tcase(s7, tc7_1);
  tcase_add_test(tc7_1, s21_strchr_test1);
  tcase_add_test(tc7_1, s21_strchr_test2);
  tcase_add_test(tc7_1, s21_strchr_test3);
  tcase_add_test(tc7_1, s21_strchr_test4);
  suite_add_tcase(s8, tc8_1);
  tcase_add_test(tc8_1, s21_strcspn_test1);
  tcase_add_test(tc8_1, s21_strcspn_test2);
  tcase_add_test(tc8_1, s21_strcspn_test3);
  tcase_add_test(tc8_1, s21_strcspn_test4);
  tcase_add_test(tc8_1, s21_strcspn_test5);
  suite_add_tcase(s9, tc9_1);
  tcase_add_test(tc9_1, s21_strerror_test1);
  tcase_add_test(tc9_1, s21_strerror_test2);
  suite_add_tcase(s10, tc10_1);
  tcase_add_test(tc10_1, s21_strlen_test1);
  tcase_add_test(tc10_1, s21_strlen_test2);
  tcase_add_test(tc10_1, s21_strlen_test3);
  tcase_add_test(tc10_1, s21_strlen_test4);
  suite_add_tcase(s11, tc11_1);
  tcase_add_test(tc11_1, s21_strncat_test1);
  tcase_add_test(tc11_1, s21_strncat_test2);
  tcase_add_test(tc11_1, s21_strncat_test3);
  suite_add_tcase(s12, tc12_1);
  tcase_add_test(tc12_1, s21_strncmp_test1);
  tcase_add_test(tc12_1, s21_strncmp_test2);
  tcase_add_test(tc12_1, s21_strncmp_test3);
  tcase_add_test(tc12_1, s21_strncmp_test4);
  tcase_add_test(tc12_1, s21_strncmp_test5);
  tcase_add_test(tc12_1, s21_strncmp_test6);
  suite_add_tcase(s13, tc13_1);
  tcase_add_test(tc13_1, s21_strncpy_test1);
  tcase_add_test(tc13_1, s21_strncpy_test2);
  tcase_add_test(tc13_1, s21_strncpy_test3);
  tcase_add_test(tc13_1, s21_strncpy_test4);
  tcase_add_test(tc13_1, s21_strncpy_test5);
  suite_add_tcase(s14, tc14_1);
  tcase_add_test(tc14_1, s21_strpbrk_test1);
  tcase_add_test(tc14_1, s21_strpbrk_test2);
  tcase_add_test(tc14_1, s21_strpbrk_test3);
  tcase_add_test(tc14_1, s21_strpbrk_test4);
  tcase_add_test(tc14_1, s21_strpbrk_test5);
  suite_add_tcase(s15, tc15_1);
  tcase_add_test(tc15_1, s21_strrchr_test1);
  tcase_add_test(tc15_1, s21_strrchr_test2);
  tcase_add_test(tc15_1, s21_strrchr_test3);
  tcase_add_test(tc15_1, s21_strrchr_test4);
  tcase_add_test(tc15_1, s21_strrchr_test5);
  suite_add_tcase(s16, tc16_1);
  tcase_add_test(tc16_1, s21_strstr_test1);
  tcase_add_test(tc16_1, s21_strstr_test2);
  tcase_add_test(tc16_1, s21_strstr_test3);
  tcase_add_test(tc16_1, s21_strstr_test4);
  tcase_add_test(tc16_1, s21_strstr_test5);
  tcase_add_test(tc16_1, s21_strstr_test6);
  suite_add_tcase(s17, tc17_1);
  tcase_add_test(tc17_1, s21_strtok_test1);
  tcase_add_test(tc17_1, s21_strtok_test2);
  tcase_add_test(tc17_1, s21_strtok_test3);
  tcase_add_test(tc17_1, s21_strtok_test4);
  tcase_add_test(tc17_1, s21_strtok_test5);
  tcase_add_test(tc17_1, s21_strtok_test6);
  suite_add_tcase(s18, tc18_1);
  tcase_add_test(tc18_1, s21_to_lower_test1);
  tcase_add_test(tc18_1, s21_to_lower_test2);
  tcase_add_test(tc18_1, s21_to_lower_test3);
  tcase_add_test(tc18_1, s21_to_lower_test4);
  tcase_add_test(tc18_1, s21_to_lower_test5);
  tcase_add_test(tc18_1, s21_to_lower_test6);
  suite_add_tcase(s19, tc19_1);
  tcase_add_test(tc19_1, s21_to_upper_test1);
  tcase_add_test(tc19_1, s21_to_upper_test2);
  tcase_add_test(tc19_1, s21_to_upper_test3);
  tcase_add_test(tc19_1, s21_to_upper_test4);
  tcase_add_test(tc19_1, s21_to_upper_test5);
  tcase_add_test(tc19_1, s21_to_upper_test6);
  tcase_add_test(tc19_1, s21_to_upper_test7);
  suite_add_tcase(s20, tc20_1);
  tcase_add_test(tc20_1, s21_trim_test1);
  tcase_add_test(tc20_1, s21_trim_test2);
  tcase_add_test(tc20_1, s21_trim_test3);
  tcase_add_test(tc20_1, s21_trim_test4);
  tcase_add_test(tc20_1, s21_trim_test5);
  tcase_add_test(tc20_1, s21_trim_test6);
  tcase_add_test(tc20_1, s21_trim_test7);
  tcase_add_test(tc20_1, s21_trim_test8);
  tcase_add_test(tc20_1, s21_trim_test9);
  tcase_add_test(tc20_1, s21_trim_test10);
  suite_add_tcase(s21, tc21_1);
  tcase_add_test(tc21_1, s21_no_valgrind_test1);
  tcase_add_test(tc21_1, s21_no_valgrind_test2);
  tcase_add_test(tc21_1, s21_no_valgrind_test3);
  tcase_add_test(tc21_1, s21_no_valgrind_test4);
  tcase_add_test(tc21_1, s21_no_valgrind_test5);
  tcase_add_test(tc21_1, s21_no_valgrind_test6);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);
  srunner_add_suite(sr, s5);
  srunner_add_suite(sr, s6);
  srunner_add_suite(sr, s7);
  srunner_add_suite(sr, s8);
  srunner_add_suite(sr, s9);
  srunner_add_suite(sr, s10);
  srunner_add_suite(sr, s11);
  srunner_add_suite(sr, s12);
  srunner_add_suite(sr, s13);
  srunner_add_suite(sr, s14);
  srunner_add_suite(sr, s15);
  srunner_add_suite(sr, s16);
  srunner_add_suite(sr, s17);
  srunner_add_suite(sr, s18);
  srunner_add_suite(sr, s19);
  srunner_add_suite(sr, s20);
  srunner_add_suite(sr, s21);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
